version: 1
grouping:
  default: adbWalletFn
variables:
  compartment_id:
    type: oci:identity:compartment:id
    required: true
  autonomous_database_id:
    type: oci:database:autonomousdatabase:id
    required: true
    dependsOn:
      required:
        - compartment_id
  wallet_password:
    type: string
    required: true
    sensitive: true
  db_user:
    type: string
    required: true
    default: admin
  fn_app_name:
    type: string
    required: true
