import React, { forwardRef } from 'react';

export const EsgReportPdf = forwardRef<HTMLDivElement>((props, ref) => {
  const blockHash = "E3B0C442...9B1B7852B855";
  const reportDate = "2026-03-18";
  const reportTimestamp = "2026-03-18T07:07:07.000Z";

  return (
    <div ref={ref} className="p-12 w-[800px] font-sans pdf-container" style={{ 
      backgroundColor: '#ffffff', 
      color: '#000000',
      '--default-border-color': 'transparent',
      '--tw-ring-color': 'transparent',
      '--tw-shadow-color': 'transparent'
    } as React.CSSProperties}>
      <style>{`
        .pdf-container *, .pdf-container *::before, .pdf-container *::after {
          border-color: inherit;
          text-decoration-color: inherit;
          outline-color: inherit;
          column-rule-color: inherit;
          caret-color: transparent;
          box-shadow: none;
          text-shadow: none;
        }
        .pdf-container {
          border-color: transparent;
          text-decoration-color: transparent;
          outline-color: transparent;
          column-rule-color: transparent;
        }
      `}</style>
      <div className="text-center mb-12">
        <div className="w-20 h-20 rounded-2xl mx-auto mb-6 flex items-center justify-center text-3xl font-bold" style={{ backgroundColor: '#009E9D', color: '#ffffff' }}>
          E
        </div>
        <h1 className="text-4xl font-bold mb-4" style={{ color: '#1e293b' }}>2026 ESG Sustainability Report</h1>
        <p className="text-xl" style={{ color: '#475569' }}>Generated by ESG GO Platform</p>
        <p className="text-sm mt-2" style={{ color: '#94a3b8' }}>Date: {reportDate}</p>
      </div>

      <div className="mb-10">
        <h2 className="text-2xl font-bold border-b-2 pb-2 mb-6" style={{ borderColor: '#e2e8f0', color: '#1e293b' }}>1. Environmental Performance</h2>
        <div className="grid grid-cols-2 gap-6">
          <div className="p-6 rounded-xl border" style={{ backgroundColor: '#f8fafc', borderColor: '#f1f5f9' }}>
            <h3 className="font-bold mb-2" style={{ color: '#334155' }}>Carbon Emissions (Scope 1 & 2)</h3>
            <p className="text-3xl font-bold" style={{ color: '#009E9D' }}>12,450 <span className="text-lg font-normal" style={{ color: '#64748b' }}>tCO2e</span></p>
            <p className="text-sm mt-2 font-medium" style={{ color: '#059669' }}>↓ 5.2% YoY</p>
          </div>
          <div className="p-6 rounded-xl border" style={{ backgroundColor: '#f8fafc', borderColor: '#f1f5f9' }}>
            <h3 className="font-bold mb-2" style={{ color: '#334155' }}>Renewable Energy Usage</h3>
            <p className="text-3xl font-bold" style={{ color: '#009E9D' }}>45.2 <span className="text-lg font-normal" style={{ color: '#64748b' }}>%</span></p>
            <p className="text-sm mt-2 font-medium" style={{ color: '#059669' }}>↑ 12% YoY</p>
          </div>
          <div className="p-6 rounded-xl border" style={{ backgroundColor: '#f8fafc', borderColor: '#f1f5f9' }}>
            <h3 className="font-bold mb-2" style={{ color: '#334155' }}>Water Consumption</h3>
            <p className="text-3xl font-bold" style={{ color: '#009E9D' }}>85,200 <span className="text-lg font-normal" style={{ color: '#64748b' }}>m³</span></p>
            <p className="text-sm mt-2 font-medium" style={{ color: '#059669' }}>↓ 2.1% YoY</p>
          </div>
          <div className="p-6 rounded-xl border" style={{ backgroundColor: '#f8fafc', borderColor: '#f1f5f9' }}>
            <h3 className="font-bold mb-2" style={{ color: '#334155' }}>Waste Recycling Rate</h3>
            <p className="text-3xl font-bold" style={{ color: '#009E9D' }}>92.5 <span className="text-lg font-normal" style={{ color: '#64748b' }}>%</span></p>
            <p className="text-sm mt-2 font-medium" style={{ color: '#059669' }}>↑ 3.4% YoY</p>
          </div>
        </div>
      </div>

      <div className="mb-10">
        <h2 className="text-2xl font-bold border-b-2 pb-2 mb-6" style={{ borderColor: '#e2e8f0', color: '#1e293b' }}>2. Social Responsibility</h2>
        <div className="grid grid-cols-2 gap-6">
          <div className="p-6 rounded-xl border" style={{ backgroundColor: '#f8fafc', borderColor: '#f1f5f9' }}>
            <h3 className="font-bold mb-2" style={{ color: '#334155' }}>Employee Training Hours</h3>
            <p className="text-3xl font-bold" style={{ color: '#219EBC' }}>45 <span className="text-lg font-normal" style={{ color: '#64748b' }}>hrs/person</span></p>
          </div>
          <div className="p-6 rounded-xl border" style={{ backgroundColor: '#f8fafc', borderColor: '#f1f5f9' }}>
            <h3 className="font-bold mb-2" style={{ color: '#334155' }}>Gender Diversity (Management)</h3>
            <p className="text-3xl font-bold" style={{ color: '#219EBC' }}>38 <span className="text-lg font-normal" style={{ color: '#64748b' }}>%</span></p>
          </div>
        </div>
      </div>

      <div className="mb-10">
        <h2 className="text-2xl font-bold border-b-2 pb-2 mb-6" style={{ borderColor: '#e2e8f0', color: '#1e293b' }}>3. Governance & Compliance</h2>
        <div className="grid grid-cols-2 gap-6">
          <div className="p-6 rounded-xl border" style={{ backgroundColor: '#f8fafc', borderColor: '#f1f5f9' }}>
            <h3 className="font-bold mb-2" style={{ color: '#334155' }}>Board Independence</h3>
            <p className="text-3xl font-bold" style={{ color: '#D4AF37' }}>60 <span className="text-lg font-normal" style={{ color: '#64748b' }}>%</span></p>
          </div>
          <div className="p-6 rounded-xl border" style={{ backgroundColor: '#f8fafc', borderColor: '#f1f5f9' }}>
            <h3 className="font-bold mb-2" style={{ color: '#334155' }}>Data Security Incidents</h3>
            <p className="text-3xl font-bold" style={{ color: '#D4AF37' }}>0</p>
          </div>
        </div>
      </div>

      <div className="mb-10 page-break">
        <h2 className="text-2xl font-bold border-b-2 pb-2 mb-6" style={{ borderColor: '#e2e8f0', color: '#1e293b' }}>4. Industry Benchmark Comparison (Top 5 Analysis)</h2>
        <p className="text-sm text-slate-500 mb-6">Comparing our metrics against the top 5 industry leaders in 2025.</p>
        
        <table className="w-full text-sm border-collapse">
          <thead>
            <tr style={{ backgroundColor: '#f1f5f9' }}>
              <th className="p-3 text-left border">Dimension</th>
              <th className="p-3 text-left border">Our Record</th>
              <th className="p-3 text-left border">Industry Avg</th>
              <th className="p-3 text-left border">Leader GAP</th>
              <th className="p-3 text-left border">Status</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td className="p-3 border font-medium">Carbon Intensity</td>
              <td className="p-3 border">12.4 tCO2e/M$</td>
              <td className="p-3 border">15.2 tCO2e/M$</td>
              <td className="p-3 border text-emerald-600">-18% Better</td>
              <td className="p-3 border"><span className="px-2 py-0.5 bg-emerald-100 text-emerald-700 rounded-full text-[10px] font-bold">LEADING</span></td>
            </tr>
            <tr>
              <td className="p-3 border font-medium">Energy Efficiency</td>
              <td className="p-3 border">84%</td>
              <td className="p-3 border">78%</td>
              <td className="p-3 border text-emerald-600">+6% Ahead</td>
              <td className="p-3 border"><span className="px-2 py-0.5 bg-emerald-100 text-emerald-700 rounded-full text-[10px] font-bold">OPTIMAL</span></td>
            </tr>
            <tr>
              <td className="p-3 border font-medium">Supply Chain Audit</td>
              <td className="p-3 border">82.5%</td>
              <td className="p-3 border">85.0%</td>
              <td className="p-3 border text-amber-600">-2.5% Under</td>
              <td className="p-3 border"><span className="px-2 py-0.5 bg-amber-100 text-amber-700 rounded-full text-[10px] font-bold">IMPROVING</span></td>
            </tr>
            <tr>
              <td className="p-3 border font-medium">Diversity index</td>
              <td className="p-3 border">38%</td>
              <td className="p-3 border">32.4%</td>
              <td className="p-3 border text-emerald-600">+5.6% Ahead</td>
              <td className="p-3 border"><span className="px-2 py-0.5 bg-emerald-100 text-emerald-700 rounded-full text-[10px] font-bold">OPTIMAL</span></td>
            </tr>
          </tbody>
        </table>
        
        <div className="mt-8 p-6 rounded-xl border-l-4" style={{ backgroundColor: '#fffbeb', borderColor: '#fbbf24' }}>
          <h4 className="font-bold text-amber-800 mb-2">AI Optimization Insight:</h4>
          <p className="text-amber-700 text-sm leading-relaxed">
            While we lead in Carbon Intensity and Energy Efficiency, our Supply Chain Audit coverage lags slightly behind the top 5 average (82.5% vs 85.0%). To reach the &quot;Tier 1 Benchmark,&quot; we recommend expanding the 5T Protocol to Tier 3 suppliers.
          </p>
        </div>
      </div>

      <div className="mt-16 pt-8 border-t text-center text-sm" style={{ borderColor: '#e2e8f0', color: '#64748b' }}>
        <p className="mb-2 font-bold">[信/Trustworthy] This report is cryptographically locked and verified by the ESG GO 5T Protocol.</p>
        <div className="flex items-center justify-center gap-4 mb-4">
           <p className="text-xs">Seal ID: OMNI-RE-2026-X77</p>
           <p className="text-xs">Timestamp: {reportTimestamp}</p>
        </div>
        <p className="font-mono text-[10px] inline-block px-4 py-1.5 rounded-lg border border-slate-100" style={{ backgroundColor: '#f8fafc' }}>
          BLOCK_HASH: {blockHash}
        </p>
      </div>
    </div>
  );
});
EsgReportPdf.displayName = 'EsgReportPdf';
