// OAG (OmniAgentGateway) TypeScript Core Interfaces & Contracts
// -----------------------------------------------------------
// This file defines the public contract for the OmniAgentGateway (OAG) layer.
// The gateway is the security boundary that enforces Hash‑Lock, Object.freeze()
// and Zero‑Illusion Validation (Transparent & Traceable).

import { IComponentCore, IHealingAction, IMutationSpec, createComponentCore } from './oab-types';

/**
 * Result returned by the gateway after a secure forward operation.
 */
export interface IGatewayResult {
  /** Status of the forwarding operation */
  status: 'forwarded' | 'blocked' | 'error';
  /** Optional hash generated by the Hash‑Lock step */
  hash?: string;
  /** Original event (immutable) */
  event?: IComponentCore;
  /** Optional error message */
  errorMessage?: string;
}

/**
 * Configuration for the Hash‑Lock algorithm.
 * Implementations may use SHA‑256, Keccak, or any cryptographic hash.
 */
export interface IHashLockConfig {
  /** Algorithm identifier, e.g. 'sha256', 'keccak256' */
  algorithm: string;
  /** Optional salt to be concatenated before hashing */
  salt?: string;
}

/**
 * Public contract exposed by the gateway.
 */
export interface IOmniGateway {
  /**
   * Securely forward an event to an external system.
   * The method performs:
   *   1️⃣ Zero‑Illusion Validation (Transparent)
   *   2️⃣ Hash‑Lock computation & Object.freeze() (Traceable)
   *   3️⃣ Optional invocation of a downstream service via HTTP / RPC.
   */
  secureForward(event: IComponentCore, opts?: { hashConfig?: IHashLockConfig }): Promise<IGatewayResult>;

  /**
   * Apply a healing action generated by OAB self‑heal hook.
   * Typical actions: restart service, rollback file, retry request,
   * dynamicPatch (adjust algorithm config), notify, etc.
   */
  applyHealing(action: IHealingAction): Promise<void>;

  /**
   * Register a custom validation hook that runs after the built‑in
   * Transparent check but before the Hash‑Lock. The hook can reject the
   * event by throwing or returning a rejected promise.
   */
  registerValidationHook(
    hook: (event: IComponentCore) => Promise<void> | void
  ): void;

  /**
   * Inject a managed mutation (Chaos Monkey) into the gateway.
   * The gateway will randomly apply the mutation according to the
   * provided probability and then emit a 'managed:mutation' event on OAB.
   */
  injectManagedMutation(mutation: IMutationSpec): void;
}

/**
 * Utility: compute a hash according to the provided configuration.
 */
export async function computeHash(
  data: string,
  config: IHashLockConfig = { algorithm: 'sha256' }
): Promise<string> {
  const crypto = await import('crypto');
  const hash = crypto.createHash(config.algorithm);
  if (config.salt) hash.update(config.salt);
  hash.update(data);
  return hash.digest('hex');
}

/**
 * Helper to freeze an object deeply (including nested objects).
 */
export function deepFreeze<T extends object>(obj: T): T {
  Object.freeze(obj);
  Object.getOwnPropertyNames(obj).forEach(name => {
    const prop = (obj as Record<string, unknown>)[name];
    if (prop && typeof prop === 'object' && !Object.isFrozen(prop)) {
      deepFreeze(prop);
    }
  });
  return obj;
}

/**
 * Factory to create a minimal gateway component that implements the
 * contract using the default hash‑lock (SHA‑256) and a simple HTTP forward.
 */
export function createGateway(): IOmniGateway {
  const validationHooks: Array<(event: IComponentCore) => Promise<void> | void> = [];
  const managedMutations: IMutationSpec[] = [];

  const gateway: IOmniGateway = {
    async secureForward(event, opts) {
      // 1️⃣ Transparent validation (custom hooks)
      for (const hook of validationHooks) {
        try {
          await hook(event);
        } catch (e) {
          return { status: 'blocked', errorMessage: (e as Error).message };
        }
      }

      // 2️⃣ Hash‑Lock & freeze
      const hash = await computeHash(JSON.stringify(event), opts?.hashConfig);
      const locked = deepFreeze({ ...event, evidence: { ...(event.evidence || {}), hash } });

      // 3️⃣ Example external forward (placeholder – real implementation may use axios/fetch)
      // Here we simply simulate a successful forward.
      return { status: 'forwarded', hash, event: locked };
    },

    async applyHealing(action) {
      // Simple dispatcher – real world would integrate with PM2, file system, etc.
      console.info(`[OAG] Applying healing action ${action.action} on ${action.target}`);
      // No‑op placeholder – extend per project needs.
    },

    registerValidationHook(hook) {
      validationHooks.push(hook);
    },

    injectManagedMutation(mutation) {
      managedMutations.push(mutation);
      // The actual mutation injection is handled by the OAG runtime (e.g., wrap HTTP, FS, exec).
    },
  };

  return gateway;
}

// -----------------------------------------------------------
// End of OAG contract definitions.
