#!/usr/bin/env python3
"""Build complete answer-database.ts from v5_full_data.json"""

import json
import os
import sys
from pathlib import Path

# Ensure project root is in path for config imports
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from esggo.config import SUSTAIN_WRITE_DIR, ensure_dirs  # noqa: E402


def esc(s: str) -> str:
    """Escape string for double-quoted TypeScript string literal."""
    if s is None:
        return ""
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', ' ').replace('\r', '')


def build_database(data_path: str = 'v5_full_data.json', output_path: str | None = None) -> None:
    """Build answer-database.ts from JSON data file."""
    if output_path is None:
        ensure_dirs()
        output_path = str(SUSTAIN_WRITE_DIR / 'answer-database.ts')

    # Validate input file
    if not os.path.exists(data_path):
        print(f"Error: Input file not found: {data_path}")
        sys.exit(1)

    with open(data_path, encoding='utf-8') as f:
        data = json.load(f)

    lines = []
    lines.append('/**')
    lines.append(' * ESGGO v5.0 — 完整資料庫 (8分頁完整集成)')
    lines.append(' * 來源: @ESG_GO_C版_10家公司_極致擬真完整模擬填答_完全對齊A版欄位.xlsx')
    lines.append(' * 規模: 10公司 × 140題 = 1400筆高擬真填答 + 9佐證指引 + 9Dashboard指標 + 12GRI映射')
    lines.append(' */')
    lines.append('')
    lines.append('// ═══════════════════════════════════════════════')
    lines.append('// Types')
    lines.append('// ═══════════════════════════════════════════════')
    lines.append('')
    lines.append('export interface CompanyProfile {')
    lines.append('  readonly instanceId: string;')
    lines.append('  readonly industryType: string;')
    lines.append('  readonly companyName: string;')
    lines.append('  readonly shortName: string;')
    lines.append('  readonly scale: string;')
    lines.append('  readonly employees: number;')
    lines.append('  readonly annualRevenue: string;')
    lines.append('  readonly operatingLocations: string;')
    lines.append('  readonly mainBusiness: string;')
    lines.append('  readonly energyUsage: string;')
    lines.append('  readonly electricityKwh: number;')
    lines.append('  readonly waterTons: number;')
    lines.append('}')
    lines.append('')
    lines.append('export interface Question {')
    lines.append('  readonly questionId: string;')
    lines.append('  readonly chapter: string;')
    lines.append('  readonly question: string;')
    lines.append('  readonly whatToFill: string;')
    lines.append('  readonly whyToFill: string;')
    lines.append('  readonly griMapping: string;')
    lines.append('  readonly evidence: string;')
    lines.append('  readonly aiHelp: string;')
    lines.append('}')
    lines.append('')
    lines.append('export interface Answer {')
    lines.append('  readonly companyId: string;')
    lines.append('  readonly companyType: string;')
    lines.append('  readonly companyName: string;')
    lines.append('  readonly questionId: string;')
    lines.append('  readonly chapter: string;')
    lines.append('  readonly question: string;')
    lines.append('  readonly answer: string;')
    lines.append('  readonly dataAtoms: string;')
    lines.append('  readonly gri: string;')
    lines.append('  readonly evidence: string;')
    lines.append('}')
    lines.append('')
    lines.append('export interface ReportOutline {')
    lines.append('  readonly instanceId: string;')
    lines.append('  readonly companyName: string;')
    lines.append('  readonly industryType: string;')
    lines.append('  readonly summary: string;')
    lines.append('  readonly envHighlight: string;')
    lines.append('  readonly socialHighlight: string;')
    lines.append('  readonly govHighlight: string;')
    lines.append('  readonly impactHighlight: string;')
    lines.append('  readonly upgradeAdvice: string;')
    lines.append('}')
    lines.append('')
    lines.append('export interface EvidenceGuide {')
    lines.append('  readonly category: string;')
    lines.append('  readonly applicableQuestions: string;')
    lines.append('  readonly suggestedUpload: string;')
    lines.append('  readonly necessity: string;')
    lines.append('  readonly purpose: string;')
    lines.append('  readonly aVersionHint: string;')
    lines.append('}')
    lines.append('')
    lines.append('export interface DashboardMetric {')
    lines.append('  readonly category: string;')
    lines.append('  readonly metricName: string;')
    lines.append('  readonly sourceQuestion: string;')
    lines.append('  readonly availableData: string;')
    lines.append('  readonly govPurpose: string;')
    lines.append('  readonly upgradeAdvice: string;')
    lines.append('}')
    lines.append('')
    lines.append('export interface GRIImpactMapping {')
    lines.append('  readonly chapter: string;')
    lines.append('  readonly mainQuestions: string;')
    lines.append('  readonly griMapping: string;')
    lines.append('  readonly investorMapping: string;')
    lines.append('  readonly aiTranslationLogic: string;')
    lines.append('}')

    # Company Profiles
    lines.append('')
    lines.append('// ═══════════════════════════════════════════════')
    lines.append('// 01_10家公司Profile')
    lines.append('// ═══════════════════════════════════════════════')
    lines.append('')
    lines.append('export const COMPANIES: readonly CompanyProfile[] = [')
    for p in data['profiles']:
        lines.append('  {')
        lines.append(f'    instanceId: "{p["instanceId"]}",')
        lines.append(f'    industryType: "{esc(p["industryType"])}",')
        lines.append(f'    companyName: "{esc(p["companyName"])}",')
        lines.append(f'    shortName: "{esc(p["shortName"])}",')
        lines.append(f'    scale: "{esc(p["scale"])}",')
        lines.append(f'    employees: {p["employees"]},')
        lines.append(f'    annualRevenue: "{esc(p["annualRevenue"])}",')
        lines.append(f'    operatingLocations: "{esc(p["operatingLocations"])}",')
        lines.append(f'    mainBusiness: "{esc(p["mainBusiness"])}",')
        lines.append(f'    energyUsage: "{esc(p["energyUsage"])}",')
        lines.append(f'    electricityKwh: {p["electricityKwh"]},')
        lines.append(f'    waterTons: {p["waterTons"]},')
        lines.append('  },')
    lines.append('];')

    # Questions
    lines.append('')
    lines.append('// ═══════════════════════════════════════════════')
    lines.append('// 02_C版140題題庫')
    lines.append('// ═══════════════════════════════════════════════')
    lines.append('')
    lines.append('export const QUESTIONS: readonly Question[] = [')
    for q in data['questions']:
        lines.append('  {')
        lines.append(f'    questionId: "{esc(q["questionId"])}",')
        lines.append(f'    chapter: "{esc(q["chapter"])}",')
        lines.append(f'    question: "{esc(q["question"][:200])}",')
        lines.append(f'    whatToFill: "{esc(q["whatToFill"][:150])}",')
        lines.append(f'    griMapping: "{esc(q["griMapping"])}",')
        lines.append(f'    evidence: "{esc(q["evidence"])}",')
        lines.append('  },')
    lines.append('];')

    # Answers (all 1400)
    lines.append('')
    lines.append('// ═══════════════════════════════════════════════')
    lines.append('// 03_C版完整填答1400筆')
    lines.append('// ═══════════════════════════════════════════════')
    lines.append('')
    lines.append('const ANSWERS: readonly Answer[] = [')
    for a in data['answers']:
        lines.append('  {')
        lines.append(f'    companyId: "{esc(a["instanceId"])}",')
        lines.append(f'    questionId: "{esc(a["questionId"])}",')
        lines.append(f'    chapter: "{esc(a["chapter"])}",')
        lines.append(f'    answer: "{esc(a["answer"][:200])}",')
        lines.append(f'    dataAtoms: "{esc(a["dataAtoms"])}",')
        lines.append(f'    gri: "{esc(a["gri"])}",')
        lines.append('  },')
    lines.append('];')

    # Functions
    lines.append('')
    lines.append('// ═══════════════════════════════════════════════')
    lines.append('// Functions')
    lines.append('// ═══════════════════════════════════════════════')
    lines.append('')
    lines.append('export function getAnswersByCompany(companyId: string): readonly Answer[] {')
    lines.append('  return ANSWERS.filter(a => a.companyId === companyId);')
    lines.append('}')
    lines.append('')
    lines.append('export function getQuestionsByChapter(chapter: string): readonly Question[] {')
    lines.append('  return QUESTIONS.filter(q => q.chapter === chapter);')
    lines.append('}')
    lines.append('')
    lines.append('export function getCompanyById(companyId: string): CompanyProfile | undefined {')
    lines.append('  return COMPANIES.find(c => c.instanceId === companyId);')
    lines.append('}')
    lines.append('')
    lines.append('export function getReportOutline(companyId: string): ReportOutline | undefined {')
    lines.append('  return REPORT_OUTLINES.find(r => r.instanceId === companyId);')
    lines.append('}')
    lines.append('')
    lines.append('export function getEvidenceGuide(category: string): EvidenceGuide | undefined {')
    lines.append('  return EVIDENCE_GUIDE.find(e => e.category === category);')
    lines.append('}')
    lines.append('')
    lines.append('export function getGRIImpact(chapter: string): GRIImpactMapping | undefined {')
    lines.append('  return GRI_IMPACT.find(g => g.chapter === chapter);')
    lines.append('}')

    # Report Outlines
    lines.append('')
    lines.append('// ═══════════════════════════════════════════════')
    lines.append('// 04_簡版ESG報告雛形')
    lines.append('// ═══════════════════════════════════════════════')
    lines.append('')
    lines.append('const REPORT_OUTLINES: readonly ReportOutline[] = [')
    for r in data['reportOutlines']:
        lines.append('  {')
        lines.append(f'    instanceId: "{esc(r["instanceId"])}",')
        lines.append(f'    companyName: "{esc(r["companyName"])}",')
        lines.append(f'    industryType: "{esc(r["industryType"])}",')
        lines.append(f'    summary: "{esc(r["summary"][:120])}",')
        lines.append(f'    envHighlight: "{esc(r["envHighlight"][:100])}",')
        lines.append(f'    socialHighlight: "{esc(r["socialHighlight"][:100])}",')
        lines.append(f'    govHighlight: "{esc(r["govHighlight"][:100])}",')
        lines.append(f'    impactHighlight: "{esc(r["impactHighlight"][:100])}",')
        lines.append(f'    upgradeAdvice: "{esc(r["upgradeAdvice"][:100])}",')
        lines.append('  },')
    lines.append('];')

    # Evidence Guide
    lines.append('')
    lines.append('// ═══════════════════════════════════════════════')
    lines.append('// 05_佐證資料與上傳指引')
    lines.append('// ═══════════════════════════════════════════════')
    lines.append('')
    lines.append('const EVIDENCE_GUIDE: readonly EvidenceGuide[] = [')
    for e in data['evidenceGuide']:
        lines.append('  {')
        lines.append(f'    category: "{esc(e["category"])}",')
        lines.append(f'    applicableQuestions: "{esc(e["applicableQuestions"])}",')
        lines.append(f'    suggestedUpload: "{esc(e["suggestedUpload"][:100])}",')
        lines.append(f'    necessity: "{esc(e["necessity"])}",')
        lines.append(f'    purpose: "{esc(e["purpose"][:100])}",')
        lines.append('  },')
    lines.append('];')

    # Dashboard Metrics
    lines.append('')
    lines.append('// ═══════════════════════════════════════════════')
    lines.append('// 06_C版Dashboard指標')
    lines.append('// ═══════════════════════════════════════════════')
    lines.append('')
    lines.append('export const DASHBOARD_METRICS: readonly DashboardMetric[] = [')
    for d in data['dashboardMetrics']:
        lines.append('  {')
        lines.append(f'    category: "{esc(d["category"])}",')
        lines.append(f'    metricName: "{esc(d["metricName"])}",')
        lines.append(f'    sourceQuestion: "{esc(d["sourceQuestion"])}",')
        lines.append(f'    availableData: "{esc(d["availableData"][:100])}",')
        lines.append(f'    govPurpose: "{esc(d["govPurpose"][:100])}",')
        lines.append('  },')
    lines.append('];')

    # GRI Impact
    lines.append('')
    lines.append('// ═══════════════════════════════════════════════')
    lines.append('// 07_GRI與Impact摘要')
    lines.append('// ═══════════════════════════════════════════════')
    lines.append('')
    lines.append('const GRI_IMPACT: readonly GRIImpactMapping[] = [')
    for g in data['griImpact']:
        lines.append('  {')
        lines.append(f'    chapter: "{esc(g["chapter"])}",')
        lines.append(f'    mainQuestions: "{esc(g["mainQuestions"])}",')
        lines.append(f'    griMapping: "{esc(g["griMapping"])}",')
        lines.append(f'    investorMapping: "{esc(g["investorMapping"])}",')
        lines.append('  },')
    lines.append('];')

    # Stats
    lines.append('')
    lines.append('// ═══════════════════════════════════════════════')
    lines.append('// 數據統計')
    lines.append('// ═══════════════════════════════════════════════')
    lines.append('')
    lines.append(f'export const TOTAL_COMPANIES = {len(data["profiles"])};')
    lines.append(f'export const TOTAL_QUESTIONS = {len(data["questions"])};')
    lines.append(f'export const TOTAL_ANSWERS = {len(data["answers"])};')
    lines.append(f'export const TOTAL_EVIDENCE_GUIDES = {len(data["evidenceGuide"])};')
    lines.append(f'export const TOTAL_DASHBOARD_METRICS = {len(data["dashboardMetrics"])};')
    lines.append(f'export const TOTAL_GRI_MAPPINGS = {len(data["griImpact"])};')

    output = '\n'.join(lines)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(output)
    print(f"answer-database.ts: {len(output):,} bytes, {len(lines):,} lines")


if __name__ == "__main__":
    build_database()
