#!/usr/bin/env bash
# Minimal Oracle Console / Run Command recovery script
set -u
echo '[status] hostname=$(hostname)'
echo '[status] whoami=$(whoami)'
echo '[status] date=$(date -Iseconds)'
echo '[network] ip_links=$(ip -brief link show || true)'
echo '[network] ip_addrs=$(ip -brief addr show || true)'
echo '[network] routes=$(ip route || true)'
echo '[network] external=$(curl -s --max-time 3 http://checkip.amazonaws.com || echo unavailable)'
echo '[service] sshd=$(systemctl is-active sshd || true)'
echo '[service] ssh_listeners=$(ss -ltnp | grep :22 || true)'
echo '[service] gateway_listeners=$(ss -ltnp | grep :8642 || true)'
echo '[service] app_listeners=$(ss -ltnp | grep :3000 || true)'
echo '[service] ufw=$(ufw status || true)'
echo '[service] networkd=$(systemctl is-active systemd-networkd || true)'
echo '[service] oracle_agent=$(systemctl is-active oracle-cloud-agent || true)'
echo '[logs] oracle_runcommand=$(sudo tail -n 20 /var/log/oracle-cloud-agent/plugins/runcommand/runcommand.log 2>/dev/null || echo no_log)'
echo '[logs] sshd_recent=$(sudo journalctl -u sshd -n 20 --no-pager 2>/dev/null || echo no_journal)'
echo '[logs] syslog_recent=$(sudo tail -n 20 /var/log/syslog 2>/dev/null || echo no_syslog)'
echo '[status] finished'
